### PR TITLE
Update ControlsFX and FXSampler to latest versions

### PR DESCRIPTION
**Pull request by abhinayagarwal**
This PR has a dependency on https://github.com/openjfx/javafx-maven-plugin/pull/95, therefore I have added WIP in its description.

### CODE REVIEW

**Comment by dlemmermann** [comment]
This still WIP?

**Comment by abhinayagarwal** [comment]
Hi Dirk,

This is not WIP if you are OK to use the snapshot version of the plugin :)

**Comment by dlemmermann** [comment]
Nah ..... it can wait. :-)

**Comment by abhinayagarwal** [comment]
This is now ready for review

**Comment by abhinayagarwal** [comment]
Github Actions is failing due to sonar issue. Not sure if its related to the changes this PR introduces.

**Pull request merged**
