### PR TITLE
Migrate to iCal4j 4

### PR DESCRIPTION
**Pull request by mkroening**
This is my initial work on migrating to the iCal4j 4 API supporting the new Java date/time API. See [iCal4j 4 and the new Java date/time API](https://ical4j.github.io/2019/06/18/ical4j-4-preview.html).

I currently use the first alpha release, which has still bugs and is not stable jet. See [iCal4j 4 Alpha Release](https://ical4j.github.io/2020/02/28/ical4j-4-alpha.html).

The main App seems to work fine, but I experience issues with the iCalApp, even without this patch. I'll look into that.

What do you think?

### CODE REVIEW

**Comment by dlemmermann** [comment]
This looks very good to me. Please proceed. FYI: I will most likely also start a new customer project very soon where I will full ical4j support. So I will only merge once everything is stable.

**Comment by dlemmermann** [comment]
Currently this PR fails btw.

**Comment by mkroening** [comment]
The PR fails because the alpha is not on the central repository. Locally all tests succeed.

For development, I built the alpha locally. I thought, it would not be worth it to set up Travis CI and LGTM to also build iCal4j. There is a build available on [GitHub Packages](https://github.com/ical4j/ical4j/packages/140027), but I could not manage to set up that repository with maven without my GitHub credentials.

**Comment by dlemmermann** [comment]
How to proceed then? I really do not want to continue without having Travis CI working.

**Comment by mkroening** [comment]
Sorry, if I was not clear about my intentions.
I wanted to draft these changes to discuss them and wait for a stable iCal4j 4 release. Then CI should succeed.

**Comment by dlemmermann** [comment]
ok. The changes look perfectly fine to me.

**Comment by dlemmermann** [comment]
Any updates here?

**Comment by mkroening** [comment]
`4.0.0-alpha2` has been released on maven central, although with API changes.
I'll make the adjustments this evening. CI should pass then.

It's up to you to decide whether to merge or to wait. I would expect more API breakages until a stable release of ical4j.

**Comment by dlemmermann** [comment]
This PR becomes quite important to me now as I want to start work on an ical SERVER module. So ideally this works soon, so that I can start leveraging it.

**Comment by mkroening** [comment]
All right. I made the necessary changes for alpha2. The build is now reproducible and working without having to build ical4j as well.

**Pull request merged**
